trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubServiceConnection: 'docker-hub-dransfeldt'
  imageName: 'dransfeldt/juice-shop'

steps:
#- script: sudo apt install google-chrome-stable
#  displayName: 'Installing Chrome'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

#- script: rm -rf node_modules && rm -rf frontend/node_modules
#  displayName: 'Remove node modules'
#- script: npm install --production
#  displayName: 'Npm install'
#- script: npm run package
#  displayName: 'Npm run'

#- script: npm install -g @angular/cli
#  displayName: 'Installing angular cli'

#- script: npm i -g standard@14 && cd frontend && npm install && cd ..
#  displayName: 'Installing npm'
#- script: npm run lint
#  displayName: 'Run lint'

- task: Docker@2
  displayName: 'Build image'
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile

- task: Docker@2
  displayName: 'Push image'
  inputs:
    containerRegistry: $(dockerHubServiceConnection)
    repository: $(imageName)
    command: push
    tags: 'test'
