trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:



- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

#- script: rm -rf node_modules && rm -rf frontend/node_modules
#  displayName: 'Remove node modules'
#- script: npm install --production
#  displayName: 'Npm install'
#- script: npm run package
#  displayName: 'Npm run'

#- script: npm install -g @angular/cli
#  displayName: 'Installing angular cli'

#- script: npm i -g standard@14 && cd frontend && npm install && cd ..
#  displayName: 'Installing npm'
#- script: npm run lint
#  displayName: 'Run lint'

- script: npm i npm -g
  displayName: 'update npm'

- script: npm -v
  displayName: 'npm check version'

- script: npm install
  displayName: 'npm install'

- script: npm audit --json > audit.json
  displayName: 'audit'

- script: npm install typescript
  displayName: 'Typescript'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'dransfeldt'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'devslop'
    cliProjectName: 'devslop'
    cliSources: '.'

- task: SonarCloudAnalyze@1
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: 'Docker: Build'
  inputs:
    containerRegistry: 'docker-hub-dransfeldt'
    repository: 'dransfeldt/juice-shop'
    command: 'Build'
    Dockerfile: 'Dockerfile'

- task: Docker@2
  displayName: 'Docker: Push'
  inputs:
    containerRegistry: 'docker-hub-dransfeldt'
    repository: 'dransfeldt/juice-shop'
    command: 'Push'