trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- script: sudo apt install google-chrome-stable
#  displayName: 'Installing Chrome'

- task: WhiteSource Bolt@19

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

#- script: rm -rf node_modules && rm -rf frontend/node_modules
#  displayName: 'Remove node modules'
#- script: npm install --production
#  displayName: 'Npm install'
#- script: npm run package
#  displayName: 'Npm run'

#- script: npm install -g @angular/cli
#  displayName: 'Installing angular cli'

#- script: npm i -g standard@14 && cd frontend && npm install && cd ..
#  displayName: 'Installing npm'
#- script: npm run lint
#  displayName: 'Run lint'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-dransfeldt'
    repository: 'dransfeldt/juice-shop'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

