trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'juice-shop'

steps:
- script: sudo apt install google-chrome-stable
  displayName: 'Installing Chrome'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: npm i -g standard@14 && cd frontend && npm install && cd ..
- script: npm run lint
  displayName: 'Installing npm'

- script: rm -rf node_modules
- script: rm -rf frontend/node_modules
- script: npm install --production
- script: npm run package
  displayName: 'Completing node.js setup'

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile

- script: echo Success
  condition: succeeded()
- script: echo Failed
  condition: failed()
