trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'juice-shop'

steps:
- script: sudo apt install google-chrome-stable
  displayName: 'Installing Chrome'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: rm -rf node_modules && rm -rf frontend/node_modules
  displayName: 'Remove node modules'
- script: npm install --production
  displayName: 'Npm install'
- script: npm run package
  displayName: 'Npm run'

- script: npm i -g standard@14 && cd frontend && npm install && cd ..
  displayName: 'Installing npm'
- script: npm run lint
  displayName: 'Run lint'

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile

- script: echo Success
  condition: succeeded()
- script: echo Failed
  condition: failed()
